# Site settings
title: Dadakhon Ortikov
telegram_username: dadakhon_09
instagram_username: dadakhon_09
name: Dadakhon Ortikov

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
# - title: Blog
#   url: http://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/dadakhon09
 - title: StackOverflow
   url: https://stackoverflow.com/users/8816098/dadakhon-ortikov
 - title: DZone
   url: https://dzone.com/users/4209411/dadakhon-09.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/dadakhon-ortikov-07a11b161/

#Any buzzword skills you want to include
skills:
 - Python
 - Django
 - API design
 - PostgreSQL
 - REST
 - Javascript
 - C/C++

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Backend developer
   start: 2019
   end: Ongoing
   employer: OSG
   description: Writing backend structure for various websites. Working with APIs to interact with frontend

#Education is required
education:
 - level: Bachelor of Computer Science
   date: 2017
   subject: Computer Science
   school: Inha University in Tashkent


#List of interesting Github repo/projects to include - optional
github:
 - dadakhon09/dadakhon09.github.io
 - dadakhon09/myshop_api
 - dadakhon09/OceanView
 - dadakhon09/dadakhon-blog
 - dadakhon09/final_chat

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/8816098/dadakhon-ortikov

intro: |
  I am an engineer with 2 years experience working in technology. I have primarily worked on the OSG, but have worked across a broad range of technologies thereon: Django, Javascript. As well as spending a reasonable amount of time building applications for the web, which has given me an exposure to a range of javascript and python technologies over the years, through jQuery, ajax, REST. <br/><br/>
  I enjoy building interesting products, with a good Product Management focus and a good emphasis on good engineering principles and clean code (having worked across differing languages on the JVM, I recognise that good code is contextual).<br/><br/>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Python</strong>: My current role uses Python as the primary language and have been building applications in Django framework for the last year. I am familiar with a range of Python libraries.<br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used Django, jQuery, Bootstrap.
